### PR TITLE
Rename LICENCE to LICENSE

### PR DESCRIPTION
**Pull request by radekg**
So the license is picked up by GitHub license info.

### CODE REVIEW

**Comment by alex-arica** [comment]
Thank you for your pull request.

On GitHub the link "View license" works for us. It goes to the LICENCE file as expected. 
Do you have any issue on your side when you click on "View licence" on GutHub?

The word licence and license (for US) are valid terms, since we are based in the UK we are ok with it:
https://dictionary.cambridge.org/dictionary/english/licence

**Comment by radekg** [comment]
Ah, I see what the problem is. You have an extra line in the license file above the Apache 2.0 header hence GitHub can't properly infer that it's an Apache 2.0 license.

**Comment by alex-arica** [comment]
Oh I see what you mean.

**Comment by alex-arica** [comment]
@radekg Thank you so much for reporting this.

I updated the file LICENCE and now we can see "Apache-2.0 License" on GitHub.

Your feedback is much appreciated.

**Pull request closed without merging**
