### PR TITLE
添加对资源请求/限制的支持

### PR DESCRIPTION
**Pull request by ylck**
Feature updates to https://github.com/reactive-tech/kubegres/issues/22 requirements, as well as opening 30007-30008 Nodeport for local use of kind clusters

### CODE REVIEW

**Comment by alex-arica** [comment]
Thank you!
I will review it on Tuesday as right now it's Monday evening in the UK.

**Comment by alex-arica** [comment]
I checked the code changes.

A new requirement that I mentioned today in the issue #22 , we will be using the same resources configuration for primary and replica Pods.

Please see an example of YAML below:
```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: pgsql
  namespace: db

spec:
  replicas: 1
  image: postgres:13
...
  resources:
      limits:
        memory: "4Gi"
        cpu: "2"
      requests:
        memory: "2Gi"
        cpu: "1"
...
```

Please modify the codes to reflect the above.

Few more changes that I would like to review are:
- In the event when an admin would like to modify the resource config of an existing cluster of Posgres Pods, we need to implement a spec-enforcer. Please see as an example what was done for "TolerationsSpecEnforcer.go".
- We need to be able to unit-test those changes. Please write a unit-test go file. You can use many example of existing unit-tests in the folder "test" (e.g. "spec_tolerations_test.go").

I am happy to help with any of the changes above. Just let me know.

**Comment by ylck** [comment]
Ok, I saw the latest requirements in issue https://github.com/reactive-tech/kubegres/issues/22, and I also know that I need to implement a spec-enforcer. 
Of course, unit-test also needs to be implemented.

**Comment by ylck** [comment]
> 好的，我在第[22](https://github.com/reactive-tech/kubegres/issues/22)期中看到了最新要求，我也知道我需要实施规格执行器。
> 当然，还需要实施单元测试。



> I checked the code changes.
> 
> A new requirement that I mentioned today in the issue #22 , we will be using the same resources configuration for primary and replica Pods.
> 
> Please see an example of YAML below:
> 
> ```
> apiVersion: kubegres.reactive-tech.io/v1
> kind: Kubegres
> metadata:
>   name: pgsql
>   namespace: db
> 
> spec:
>   replicas: 1
>   image: postgres:13
> ...
>   resources:
>       limits:
>         memory: "4Gi"
>         cpu: "2"
>       requests:
>         memory: "2Gi"
>         cpu: "1"
> ...
> ```
> 
> Please modify the codes to reflect the above.
> 
> Few more changes that I would like to review are:
> 
> * In the event when an admin would like to modify the resource config of an existing cluster of Posgres Pods, we need to implement a spec-enforcer. Please see as an example what was done for "TolerationsSpecEnforcer.go".
> * We need to be able to unit-test those changes. Please write a unit-test go file. You can use many example of existing unit-tests in the folder "test" (e.g. "spec_tolerations_test.go").
> 
> I am happy to help with any of the changes above. Just let me know.

As required ResourceSpecEnforcer.go && spec_resource_test.go code has been updated and passed all tests for this change

**Comment by ylck** [comment]
> > 好的，我在第[22](https://github.com/reactive-tech/kubegres/issues/22)期中看到了最新要求，我也知道我需要实施规范执行器。
> > 当然，还需要实施单元测试。
> 
> > 我检查了代码更改。
> > 我今天在 issue [#22 中](https://github.com/reactive-tech/kubegres/issues/22)提到的一个新要求，我们将对主 Pod 和副本 Pod 使用相同的资源配置。
> > 请参阅下面的 YAML 示例：
> > ```
> > apiVersion: kubegres.reactive-tech.io/v1
> > kind: Kubegres
> > metadata:
> >   name: pgsql
> >   namespace: db
> > 
> > spec:
> >   replicas: 1
> >   image: postgres:13
> > ...
> >   resources:
> >       limits:
> >         memory: "4Gi"
> >         cpu: "2"
> >       requests:
> >         memory: "2Gi"
> >         cpu: "1"
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请修改代码以反映上述内容。
> > 我想回顾的更多变化是：
> > 
> > * 如果管理员想要修改现有 Posgres Pod 集群的资源配置，我们需要实现规范执行器。请以“TolerationsSpecEnforcer.go”为例。
> > * 我们需要能够对这些更改进行单元测试。请编写一个单元测试 go 文件。您可以使用文件夹“test”（例如“spec_tolerations_test.go”）中现有单元测试的许多示例。
> > 
> > 我很乐意为上述任何更改提供帮助。只要让我知道。
> 
> 根据需要，ResourceSpecEnforcer.go && spec_resource_test.go 代码已更新并通过了此更改的所有测试

In addition, the time to run the test is really very long

**Comment by ylck** [comment]
> > 好的，我在第[22](https://github.com/reactive-tech/kubegres/issues/22)期中看到了最新要求，我也知道我需要实施规格执行器。
> > 当然，还需要实施单元测试。
> 
> > I checked the code changes.
> > A new requirement that I mentioned today in the issue #22 , we will be using the same resources configuration for primary and replica Pods.
> > Please see an example of YAML below:
> > ```
> > apiVersion: kubegres.reactive-tech.io/v1
> > kind: Kubegres
> > metadata:
> >   name: pgsql
> >   namespace: db
> > 
> > spec:
> >   replicas: 1
> >   image: postgres:13
> > ...
> >   resources:
> >       limits:
> >         memory: "4Gi"
> >         cpu: "2"
> >       requests:
> >         memory: "2Gi"
> >         cpu: "1"
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please modify the codes to reflect the above.
> > Few more changes that I would like to review are:
> > 
> > * In the event when an admin would like to modify the resource config of an existing cluster of Posgres Pods, we need to implement a spec-enforcer. Please see as an example what was done for "TolerationsSpecEnforcer.go".
> > * We need to be able to unit-test those changes. Please write a unit-test go file. You can use many example of existing unit-tests in the folder "test" (e.g. "spec_tolerations_test.go").
> > 
> > I am happy to help with any of the changes above. Just let me know.
> 
> As required ResourceSpecEnforcer.go && spec_resource_test.go code has been updated and passed all tests for this change



> > Ok, I saw the latest requirements in issue #22, and I also know that I need to implement a spec-enforcer.
> > Of course, unit-test also needs to be implemented.
> 
> > I checked the code changes.
> > A new requirement that I mentioned today in the issue #22 , we will be using the same resources configuration for primary and replica Pods.
> > Please see an example of YAML below:
> > ```
> > apiVersion: kubegres.reactive-tech.io/v1
> > kind: Kubegres
> > metadata:
> >   name: pgsql
> >   namespace: db
> > 
> > spec:
> >   replicas: 1
> >   image: postgres:13
> > ...
> >   resources:
> >       limits:
> >         memory: "4Gi"
> >         cpu: "2"
> >       requests:
> >         memory: "2Gi"
> >         cpu: "1"
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please modify the codes to reflect the above.
> > Few more changes that I would like to review are:
> > 
> > * In the event when an admin would like to modify the resource config of an existing cluster of Posgres Pods, we need to implement a spec-enforcer. Please see as an example what was done for "TolerationsSpecEnforcer.go".
> > * We need to be able to unit-test those changes. Please write a unit-test go file. You can use many example of existing unit-tests in the folder "test" (e.g. "spec_tolerations_test.go").
> > 
> > I am happy to help with any of the changes above. Just let me know.
> 
> As required ResourceSpecEnforcer.go && spec_resource_test.go code has been updated and passed all tests for this change

In addition, the time to run the test is really very long

**Comment by alex-arica** [comment]
Great thank you so much for your help.

I will review your changes on Monday morning UK time.

**Review by alex-arica — APPROVED** [review]
Great changes. Thank you for your help. I approved your PR.

**Comment by alex-arica** [comment]
Thank you very much for your help by implementing this feature!

I merged your changes into the main branch. 

I will run some tests and once satisfactory I will prepare a release tomorrow morning (UK time).

**Pull request merged**
